services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pastel-pg:/var/lib/postgresql/data

volumes:
  pastel-pg:
